
export const HOME_VIEW = 'HOME_VIEW';
export const BEATS_VIEW = 'BEATS_VIEW';


export const CONTACT_TYPING = 'CONTACT_TYPING';
export const CONTACT_SEND_PENDING = 'CONTACT_SEND_PENDING';
export const CONTACT_SEND_SUCCESS = 'CONTACT_SEND_SUCCESS';
export const CONTACT_SEND_FAILED = 'CONTACT_SEND_FAILED';


export const PURCHASE_PENDING = 'PURCHASE_PENDING';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILED = 'PURCHASE_FAILED';


export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHOOSE_LICENSE = 'CHOOSE_LICENSE';


export const LEASE_POPUP = 'LEASE_POPUP';
export const EXCLUSIVE_POPUP = 'EXCLUSIVE_POPUP';
export const CART_POPUP = 'CART_POPUP';
export const ADD_TO_CART_POPUP = 'ADD_TO_CART_POPUP';
export const SUCCESS_POPUP = 'SUCCESS_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';


export const PLAY_SONG_FEATURED = 'PLAY_SONG_FEATURED';
export const PLAY_SONG_SELECTED = 'PLAY_SONG_SELECTED';


export const ITEM_CHOOSE_LICENSE = 'ITEM_CHOOSE_LICENSE';


export const WAV_LICENSE = 'WAV_LICENSE';
export const TRACK_OUT_LICENSE = 'TRACK_OUT_LICENSE';
export const EXCLUSIVE_LICENSE = 'EXCLUSIVE_LICENSE';